extensions:
    pim-rule-index-create-button:
        module: pim/common/redirect
        parent: pim-rule-index
        targetZone: buttons
        position: 50
        aclResourceId: basecom_rule_create
        config:
            label: basecom.rules_engine.menu_entry
            route: basecom_rule_create
            buttonClass: AknButton AknButton--apply create-new-rule

    pim-rule-index-pagination-bottom:
        module: oro/datagrid/pagination-input
        parent: pim-rule-index
        targetZone: bottom-panel
        config:
            gridName: rule-grid
